# We run the index.js and put the result in the README.md file and put to github repo every day
name: Deploy

on:
  schedule:
    - cron: '15' 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node index.js

      - name: Commit files
        run: |
            git config --local user.email "info@sebastienmerv.be"
            git config --local user.name "Sebastien Merveille"
            git add README.md
            git commit -m "Update README.md"
            git push